-- Run once in a NEW hosted Supabase project (not over the legacy schema).
begin;
create schema if not exists private;
revoke all on schema private from public;
create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 name text check (char_length(name)<=100),
 bio text check (char_length(bio)<=1000),
 avatar_url text check (char_length(avatar_url)<=2048),
 is_public boolean not null default true,
 created_at timestamptz not null default now()
);
create table public.books (
 id integer generated by default as identity primary key,
 title text not null check (char_length(btrim(title)) between 1 and 1000),
 author text check (char_length(author)<=2000), isbn text,
 cover_url text check (char_length(cover_url)<=2048),
 source text not null default 'openlibrary' check (source in ('openlibrary','manual')),
 external_id text, description text check (char_length(description)<=50000),
 published_date text, number_of_pages integer check (number_of_pages>0),
 created_at timestamptz not null default now(),
 unique(source,external_id),
 check (source<>'openlibrary' or (external_id is not null and external_id ~ '^/works/OL[0-9]+W$'))
);
create index books_isbn_idx on public.books(isbn);
create table public.user_books (
 id integer generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 book_id integer not null references public.books(id) on delete cascade,
 status text not null default 'to_read' check(status in ('to_read','reading','read')),
 current_page integer not null default 0 check(current_page>=0),
 finished_at timestamptz, added_at timestamptz not null default now(),
 unique(user_id,book_id)
);
create index user_books_book_idx on public.user_books(book_id);
create index user_books_finished_idx on public.user_books(user_id,finished_at);
create table public.ratings (
 id integer generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 book_id integer not null references public.books(id) on delete cascade,
 rating smallint not null check(rating between 1 and 5),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(user_id,book_id)
);
create index ratings_book_idx on public.ratings(book_id);
create table public.reviews (
 id integer generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 book_id integer not null references public.books(id) on delete cascade,
 body text not null check(char_length(btrim(body)) between 1 and 10000),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(user_id,book_id)
);
create index reviews_book_idx on public.reviews(book_id);
create index reviews_created_idx on public.reviews(created_at desc);
create table public.lists (
 id integer generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 name text not null check(char_length(btrim(name)) between 1 and 100),
 description text check(char_length(description)<=2000),
 is_public boolean not null default false, created_at timestamptz not null default now(),
 unique(user_id,name)
);
create table public.list_books (
 id integer generated by default as identity primary key,
 list_id integer not null references public.lists(id) on delete cascade,
 book_id integer not null references public.books(id) on delete cascade,
 added_at timestamptz not null default now(), unique(list_id,book_id)
);
create index list_books_book_idx on public.list_books(book_id);
create table public.reading_goals (
 id integer generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 year integer not null check(year between 2000 and 2200),
 target_books integer not null check(target_books>0),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(user_id,year)
);
create table public.follows (
 follower_id uuid not null,
 following_id uuid not null,
 created_at timestamptz not null default now(),
 primary key(follower_id,following_id),
 constraint follows_follower_id_fkey foreign key(follower_id) references public.profiles(id) on delete cascade,
 constraint follows_following_id_fkey foreign key(following_id) references public.profiles(id) on delete cascade,
 constraint follows_no_self_follow check(follower_id<>following_id)
);
create index follows_following_idx on public.follows(following_id,follower_id);
create function private.handle_new_user() returns trigger
language plpgsql security definer set search_path='' as $$
begin
 insert into public.profiles(id,name)
 values(new.id,nullif(left(btrim(new.raw_user_meta_data->>'name'),100),''));
 return new;
end; $$;
revoke all on function private.handle_new_user() from public;
create trigger on_auth_user_created after insert on auth.users
 for each row execute function private.handle_new_user();
insert into public.profiles(id,name)
 select id,nullif(left(btrim(raw_user_meta_data->>'name'),100),'') from auth.users
 on conflict(id) do nothing;
create function private.touch_updated_at() returns trigger
language plpgsql set search_path='' as $$
begin new.updated_at=now(); return new; end; $$;
revoke all on function private.touch_updated_at() from public;
create trigger ratings_touch before update on public.ratings for each row execute function private.touch_updated_at();
create trigger reviews_touch before update on public.reviews for each row execute function private.touch_updated_at();
create trigger goals_touch before update on public.reading_goals for each row execute function private.touch_updated_at();
-- Database owns finished_at transitions, including direct Data API writes.
create function private.track_completion() returns trigger
language plpgsql set search_path='' as $$
begin
 if new.status <> 'read' then new.finished_at=null;
 elsif TG_OP='INSERT' then new.finished_at=coalesce(new.finished_at,now());
 elsif old.status <> 'read' then new.finished_at=now();
 else new.finished_at=coalesce(old.finished_at,now()); end if;
 return new;
end; $$;
revoke all on function private.track_completion() from public;
create trigger completion before insert or update on public.user_books
 for each row execute function private.track_completion();
-- RLS + explicit grants on every exposed table.
do $$ declare t text; begin
 foreach t in array array['profiles','books','user_books','ratings','reviews','lists','list_books','reading_goals','follows'] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('revoke all on public.%I from anon,authenticated',t);
 end loop;
end $$;
grant usage on schema public to anon,authenticated,service_role;
grant select on public.profiles,public.books,public.user_books,public.ratings,public.reviews,public.lists,public.list_books to anon,authenticated;
grant update(name,bio,avatar_url,is_public) on public.profiles to authenticated;
grant insert,update,delete on public.user_books,public.ratings,public.reviews,public.lists,public.list_books to authenticated;
grant select,insert,update,delete on public.reading_goals to authenticated;
grant select,insert,delete on public.follows to authenticated;
create policy profiles_read on public.profiles for select to anon,authenticated
 using(is_public or id=(select auth.uid()));
create policy profiles_update on public.profiles for update to authenticated
 using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy books_read on public.books for select to anon,authenticated using(true);
do $$ declare t text; begin
 foreach t in array array['user_books','ratings','reviews'] loop
  execute format('create policy %I on public.%I for select to anon,authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.profiles p where p.id=user_id and p.is_public))',t||'_read',t);
 end loop;
 foreach t in array array['user_books','ratings','reviews','lists','reading_goals'] loop
  execute format('create policy %I on public.%I for insert to authenticated with check(user_id=(select auth.uid()))',t||'_insert',t);
  execute format('create policy %I on public.%I for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()))',t||'_update',t);
  execute format('create policy %I on public.%I for delete to authenticated using(user_id=(select auth.uid()))',t||'_delete',t);
 end loop;
end $$;
create policy lists_read on public.lists for select to anon,authenticated
 using(user_id=(select auth.uid()) or (is_public and exists(select 1 from public.profiles p where p.id=user_id and p.is_public)));
create policy goals_read on public.reading_goals for select to authenticated using(user_id=(select auth.uid()));
create policy list_books_read on public.list_books for select to anon,authenticated
 using(exists(select 1 from public.lists l where l.id=list_id));
create policy list_books_insert on public.list_books for insert to authenticated
 with check(exists(select 1 from public.lists l where l.id=list_id and l.user_id=(select auth.uid())));
create policy list_books_update on public.list_books for update to authenticated
 using(exists(select 1 from public.lists l where l.id=list_id and l.user_id=(select auth.uid())))
 with check(exists(select 1 from public.lists l where l.id=list_id and l.user_id=(select auth.uid())));
create policy list_books_delete on public.list_books for delete to authenticated
 using(exists(select 1 from public.lists l where l.id=list_id and l.user_id=(select auth.uid())));
create policy follows_read on public.follows for select to authenticated using(true);
create policy follows_insert on public.follows for insert to authenticated with check(follower_id=(select auth.uid()));
create policy follows_delete on public.follows for delete to authenticated using(follower_id=(select auth.uid()));
grant usage on sequence public.user_books_id_seq,public.ratings_id_seq,public.reviews_id_seq,public.lists_id_seq,public.list_books_id_seq,public.reading_goals_id_seq to authenticated;
grant all on public.profiles,public.books,public.user_books,public.ratings,public.reviews,public.lists,public.list_books,public.reading_goals,public.follows to service_role;
grant usage,select on sequence public.books_id_seq,public.user_books_id_seq,public.ratings_id_seq,public.reviews_id_seq,public.lists_id_seq,public.list_books_id_seq,public.reading_goals_id_seq to service_role;
-- Views/functions run with caller permissions and respect RLS.
create view public.list_summaries with(security_invoker=true) as
 select l.*,count(lb.id)::integer as book_count from public.lists l
 left join public.list_books lb on lb.list_id=l.id group by l.id;
revoke all on public.list_summaries from anon,authenticated;
grant select on public.list_summaries to anon,authenticated;
create function public.rating_summary(p_book_id integer) returns jsonb
language sql stable security invoker set search_path='' as $$
 select jsonb_build_object('count',count(*),'average',avg(rating),
 'myRating',max(rating) filter(where user_id=(select auth.uid())))
 from public.ratings where book_id=p_book_id;
$$;
create function public.profile_summary(p_user_id uuid) returns jsonb
language sql stable security invoker set search_path='' as $$
 select jsonb_build_object(
 'statusCounts',(select jsonb_build_object(
  'to_read',count(*) filter(where status='to_read'),
  'reading',count(*) filter(where status='reading'),
  'read',count(*) filter(where status='read')) from public.user_books where user_id=p_user_id),
 'stats',(select jsonb_build_object(
  'books_this_year',count(*) filter(where ub.status='read' and extract(year from ub.finished_at)=extract(year from now())),
  'pages_read',coalesce(sum(b.number_of_pages) filter(where ub.status='read'),0),
  'average_rating_given',(select avg(rating) from public.ratings where user_id=p_user_id))
  from public.user_books ub join public.books b on b.id=ub.book_id where ub.user_id=p_user_id));
$$;
create function public.goal_progress(p_year integer) returns bigint
language sql stable security invoker set search_path='' as $$
 select count(*) from public.user_books where user_id=(select auth.uid())
 and status='read' and extract(year from finished_at)=p_year;
$$;
revoke all on function public.rating_summary(integer),public.profile_summary(uuid),public.goal_progress(integer) from public,anon,authenticated;
grant execute on function public.rating_summary(integer),public.goal_progress(integer) to authenticated;
grant execute on function public.profile_summary(uuid) to anon,authenticated;
commit;
